# Generated by Django 5.0.6 on 2024-05-26 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('points', models.IntegerField(default=0)),
                ('qr_code_image', models.ImageField(blank=True, upload_to='qr_codes/')),
            ],
        ),
    ]
